linters:
  # disable:
    # Removed deprecated linters
    # - deadcode
    # - structcheck
    # - varcheck
    # - golint

  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Optional ones we want to include
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/kunwardeep/paralleltest
  misspell:
    locale: US

  govet:
    enable:
      - shadow

