linters:
  disable:
    # Remove deprecated linters
    - deadcode # deprecated: replaced by 'unused'
    - structcheck # deprecated: replaced by 'unused'
    - varcheck # deprecated: replaced by 'unused'
    - golint # deprecated: replaced by 'revive'

  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Optional ones we want to include
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - golint
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/kunwardeep/paralleltest
  misspell:
    local: US
    ignore-words:

  govet:
    check-shadowing: true

output:
  format: colored-line-number
